// Generated by CoffeeScript 1.9.3
(function() {
  define(['jquery', 'lib/mylib1'], function($, mylib1) {
    var f0, g0;
    f0 = function() {
      return console.log("a function f0 defined in mylib0: calls " + mylib1.from);
    };
    g0 = function() {
      return console.log("a function g0 defined in mylib0: uses jQuery: text of 'p': " + ($('p').text()));
    };
    return {
      f0: f0,
      g0: g0
    };
  });

}).call(this);
