// Generated by CoffeeScript 1.9.3
(function() {
  requirejs.config({
    baseUrl: 'scripts/vendor',
    paths: {
      lib: '../lib'
    }
  });

  requirejs(['jquery', 'lib/mylib0', 'lib/mylib1'], function($, mylib0, mylib1) {
    $('#main').click(function() {
      return console.log("main: calls " + mylib1.from);
    });
    $('#f0').click(function() {
      return mylib0.f0();
    });
    return $('#g0').click(function() {
      return mylib0.g0();
    });
  });

}).call(this);
